FROM alpine:3.21 AS build

COPY ./frontend /build
WORKDIR /build
RUN \
  apk add --no-cache nodejs npm && \
  npm install && \
  npm run build


FROM nginx:1.27
COPY --from=build /build/dist /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
