start: item (";" item)*
empty:
item: field operator value
field: WORD
?value: datetime
      | STR
      | empty
operator: ILIKE
        | GT
        | GEQ
        | LT
        | LEQ
datetime: /(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d\.\d+([+-][0-2]\d:[0-5]\d|Z))|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d([+-][0-2]\d:[0-5]\d|Z))|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d([+-][0-2]\d:[0-5]\d|Z))/

ILIKE: "~="
GT: ">"
GEQ: ">="
LT: "<"
LEQ: "<="
STR: /[^;]+/

%import common.WORD
